name: Update GitHub Trends Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *' # Runs at 23:00 UTC, which is 7:00 AM Beijing time

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: tell me the key
        run: echo "SHINYAPPS_TOKEN is ${{secrets.SHINYAPPS_TOKEN}}"

      - name: tell me the key2
        run: echo "SHINYAPPS_SECRET is ${{secrets.SHINYAPPS_SECRET}}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3' # Or 'release', '4.3', etc.

          
      # Add this step to install the missing system dependency
      - name: Install system dependencies for V8
        run: sudo apt-get update && sudo apt-get install -y libnode-dev

      - name: Echo R Version (R expression)
        run: Rscript -e "cat(R.version.string, '\n')"

      - name: Install renv and restore packages
        run: |
          Rscript -e "install.packages('renv')"
          Rscript -e "renv::restore()"


      - name: Run data download script
        run: Rscript download_data.R

      - name: shinyapps deploy
        run: |
             Rscript -e "rsconnect::setAccountInfo(name='tonyflying', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')""
             Rscript -e "rsconnect::deployApp(appName = 'github_trend',account = 'tonyflying', server = 'shinyapps.io', forceUpdate = TRUE)""
  

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git add github_trends.csv
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push      

