name: Update GitHub Trends Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *' # Runs at 23:00 UTC, which is 7:00 AM Beijing time

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install renv and restore packages
        run: |
          Rscript -e "install.packages('renv')"
          Rscript -e "renv::restore()"


      - name: Run data download script
        run: Rscript download_data.R

        

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git add github_trends.csv
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push      

      - name: shinyapps deploy
        run: |
             rsconnect::setAccountInfo(name='shahronak', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
             rsconnect::deployApp(appName = 'github_trend',account = 'tonyflying', server = 'shinyapps.io', forceUpdate = TRUE)
        shell: Rscript {0}